/************************************************************
 *                                                          *
 * Contents of file Copyright (c) Prelert Ltd 2006-2010     *
 *                                                          *
 *----------------------------------------------------------*
 *----------------------------------------------------------*
 * WARNING:                                                 *
 * THIS FILE CONTAINS UNPUBLISHED PROPRIETARY               *
 * SOURCE CODE WHICH IS THE PROPERTY OF PRELERT LTD AND     *
 * PARENT OR SUBSIDIARY COMPANIES.                          *
 * PLEASE READ THE FOLLOWING AND TAKE CAREFUL NOTE:         *
 *                                                          *
 * This source code is confidential and any person who      *
 * receives a copy of it, or believes that they are viewing *
 * it without permission is asked to notify Prelert Ltd     *
 * on +44 (0)20 3567 1249 or email to legal@prelert.com.    *
 * All intellectual property rights in this source code     *
 * are owned by Prelert Ltd.  No part of this source code   *
 * may be reproduced, adapted or transmitted in any form or *
 * by any means, electronic, mechanical, photocopying,      *
 * recording or otherwise.                                  *
 *                                                          *
 *----------------------------------------------------------*
 *                                                          *
 *                                                          *
 ***********************************************************/

package com.prelert.client.event;

import com.extjs.gxt.ui.client.event.ComponentEvent;
import com.prelert.client.gxt.ModuleComponent;
import com.prelert.splash.NavigationBar;


/**
 * An event generated by the navigation bar, such as clicking on a module or 
 * log out link, or firing a search.
 * @author Pete Harverson
 */
public class NavigationBarEvent extends ComponentEvent
{
	private ModuleComponent	m_Module;
	
	
	/**
	 * Creates a new NavigationBarEvent.
	 * @param container the navigation bar that is the source of the event.
	 */
	public NavigationBarEvent(NavigationBar container)
    {
		super(container);
    }
	
	
	/**
	 * Creates a new NavigationBarEvent.
	 * @param container the navigation bar that is the source of the event.
	 * @param module the target module e.g. the Explorer module if the user has
	 * clicked on the Explorer link in the Navigation bar.
	 */
	public NavigationBarEvent(NavigationBar container, ModuleComponent module)
    {
	    super(container);
	    m_Module = module;
    }
	
	
	/**
	 * Returns the target module of the event. For example, if the user has 
	 * clicked on the link to the Explorer module, the Explorer ModuleComponent 
	 * will be returned. 
	 * @return the target module, or <code>null</code> if the event is not linking
	 * to a specific module e.g. the Log Out link.
	 */
	public ModuleComponent getModule()
	{
		return m_Module;
	}

}
