[[ml-open-close-job]]
=== Open / Close Job APIs

An anomaly detection job must be opened in order for it to be ready to receive and analyze data.
A job may be opened and closed multiple times throughout its lifecycle.

The following example will open and close the `my_analysis` anomaly detection job.

[source,js]
--------------------------------------------------
POST _xpack/ml/anomaly_detectors/my_analysis/_open

POST _xpack/ml/anomaly_detectors/my_analysis/_close
--------------------------------------------------
// CONSOLE
// TEST[skip:todo]



==== Opening a job

A job must be opened in order to it to accept and analyze data.

When a new job is opened, it will start with an empty model.

When opening an existing job, the most recent model state will be automatically loaded.
This job is now ready to resume its analysis from where it left off, once new data is received.

The open job API accepts the following parameters.

[cols=",^,^,", options="header"]
|======
| Name                | Required | Default  | Description

| `open_timeout`      | no       | 30 min   | Controls the time to wait until a job has opened

| `ignore_downtime`   | no       | true     | If `true` then any gap in data since it was last closed
                                              is treated as a maintenance window i.e. not an anomaly

|======



==== Closing a job

A job can be closed once all data has been analyzed.

Closing a job will run housekeeping tasks such as pruning model history, flushing buffers, calculating final results
and persisting the internal models.
Depending upon the size of the job, it could take several minutes to close and the equivalent time to re-open.

Once closed, the anomaly detection job has almost no overhead on the cluster (except for maintaining its meta data).
A closed job is blocked for receiving data and analysis operations, however you can still explore and navigate results.

The close job API accepts the following parameters:

[cols=",^,^,", options="header"]
|======
| Name                | Required | Default  | Description

| `close_timeout`     | no       | 30 min   | Controls the time to wait until a job has closed

|======

NOTE:
If using the {prelert} UI, the job will be automatically closed when stopping a datafeed job.
